name: wasmtime
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0-290.1.beta

# Add regular dependencies here.
dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  hooks: ^1.0.0
  logging: ^1.3.0
  native_toolchain_c: ^0.17.3
  path: ^1.9.1

dev_dependencies:
  ffigen: ^20.0.0
  lints: ^6.0.0
  test: ^1.25.6
