name: wasmtime
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  hooks: ^1.0.0
  native_toolchain_c: ^0.17.3
  path: ^1.9.0

dev_dependencies:
  ffigen: ^20.0.0
  lints: ^6.0.0
  test: ^1.25.6

ffigen:
  name: WasmtimeBindings
  description: Bindings for wasmtime.
  output: 'lib/src/wasmtime_bindings.dart'
  headers:
    entry-points:
      - 'src/wasmtime-v38.0.3-x86_64-linux-c-api/include/wasmtime.h'
  compiler-opts:
    - '-Isrc/wasmtime-v38.0.3-x86_64-linux-c-api/include'
  functions:
    include:
      - wasm_engine_new
      - wasm_engine_delete
      - wasmtime_wat2wasm
      - wasmtime_error_message
      - wasmtime_error_delete
      - wasm_byte_vec_delete
      - wasm_byte_vec_new_uninitialized
